### ISSUE TITLE
能不能传一下gym/102700/problem/C的代码

### ISSUE THREAD

**Issue by IcecreamArtist** [IcecreamArtist/Upper_bound#9]
如题，或者讲一下思路

**Comment by wendavid552** [comment]
思路如下：
考虑实际上这个问题就是要求$\sum_{i=1}^n\limitsf(i)$，其中$f(i)$表示长度为$i$的、最小循环节长度是$i$（或者说就是不循环）的串的个数。
那么我们如果设$F(x)$表示长度为$x$的串的个数（所有！），显然一个不循环串重复几遍就会构成剩下的串，那么我们有$F(x)=\sum_{d|x}\limits f(d)$，那么就可以直接莫比乌斯反演，然后求一个莫比乌斯函数前缀和就可以直接算了！

**Comment by wendavid552** [comment]
I've commit this: 8493a94a9984b542b1b28cd4f324d206432d16f6, please view my code. @IcecreamArtist 
And it's really annoyed that GitHub does not support MathJax, and the mathematical formulas look really strange.
